name: Build and Push (Docker Image)

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
env:
  DOCKER_USERNAME: jake4
  DOCKER_IMAGE_NAME: youtube-audio-download-api
  DOCKER_REGISTRY_URL: docker-registry.jack.lat
  REST_PORT: 8080
  DATABASE_URL: "file:./dev.db"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract version from tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image (for ${{ env.DOCKER_IMAGE_NAME }})
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deployments/.dockerfile
          push: true
          build-args: |
            REST_PORT=${{ env.REST_PORT }}
            DATABASE_URL=${{ env.DATABASE_URL }}
          tags: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest